apiVersion: v1
kind: Namespace
metadata:
  name: ch-bot

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: telegram-bot-global
subjects:
- kind: ServiceAccount
  name: telegram-bot
  namespace: ch-bot
roleRef:
  kind: ClusterRole
  name: telegram-bot
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
    name: telegram-bot
rules:
- apiGroups: ["extensions"]
  resources: ["deployments"]
  verbs: ["list", "get", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list", "get", "watch"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegram-bot
  namespace: ch-bot
